# Generated by Django 6.1.1 on 2026-09-29 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cathedra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('head', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('role', models.CharField()),
                ('degree', models.CharField()),
                ('cathedra_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.cathedra')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name', models.CharField()),
                ('description', models.CharField()),
                ('coordinator_name', models.CharField()),
                ('coordinator_contact', models.CharField()),
                ('discipline_list', models.JSONField(default=list)),
                ('graduation_cathedra_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.cathedra')),
            ],
        ),
    ]
