# Generated by Django 6.1.1 on 2026-09-29 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturer',
            old_name='cathedra_id',
            new_name='cathedra',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='graduation_cathedra_id',
            new_name='graduation_cathedra',
        ),
    ]
