# Generated by Django 6.1.1 on 2026-10-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_rename_cathedra_id_lecturer_cathedra_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(default='Факультет природничих наук', max_length=255, verbose_name='Назва факультету')),
                ('description', models.TextField(help_text='Основний текст про місію, лабораторії та наукові дослідження факультету', verbose_name='Опис факультету')),
                ('address', models.CharField(default='04070, м. Київ, вул. Григорія Сковороди, 2, корпус 3, кімн. 216', max_length=255, verbose_name='Адреса деканату')),
                ('phone', models.CharField(default='+38 (044) 425-60-57', max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(default='fprn@ukma.edu.ua', max_length=254, verbose_name='Email')),
                ('working_hours', models.CharField(default='Пн–Пт: 09:00 – 17:00', max_length=255, verbose_name='Графік роботи')),
            ],
        ),
        migrations.AlterField(
            model_name='cathedra',
            name='head',
            field=models.CharField(max_length=255, verbose_name='Завідувач кафедри'),
        ),
        migrations.AlterField(
            model_name='cathedra',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Назва кафедри'),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='degree',
            field=models.CharField(max_length=255, verbose_name='Вчене звання'),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='name',
            field=models.CharField(max_length=255, verbose_name="Ім'я викладача"),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='role',
            field=models.CharField(max_length=255, verbose_name='Посада'),
        ),
        migrations.AlterField(
            model_name='program',
            name='code',
            field=models.IntegerField(verbose_name='Код спеціальності'),
        ),
        migrations.AlterField(
            model_name='program',
            name='coordinator_contact',
            field=models.CharField(max_length=255, verbose_name='Контакт координатору набору'),
        ),
        migrations.AlterField(
            model_name='program',
            name='coordinator_name',
            field=models.CharField(max_length=255, verbose_name="Ім'я координатору набору"),
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.TextField(verbose_name='Опис спеціальності'),
        ),
        migrations.AlterField(
            model_name='program',
            name='discipline_list',
            field=models.JSONField(default=list, verbose_name='Список дисциплін'),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Назва спеціальності'),
        ),
    ]
