# Generated by Django 6.1.1 on 2026-10-03 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_mainpageinfo_alter_cathedra_head_alter_cathedra_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cathedra',
            new_name='Department',
        ),
    ]
