# Generated by Django 6.1.1 on 2026-10-03 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_rename_cathedra_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='graduation_cathedra',
            new_name='graduation_department',
        ),
    ]
