# Generated by Django 6.1.1 on 2026-10-03 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0005_rename_graduation_cathedra_program_graduation_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='graduation_department',
            new_name='department',
        ),
    ]
