# Generated by Django 6.1.1 on 2026-10-03 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0006_rename_graduation_department_program_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='discipline_list',
            new_name='disciplines',
        ),
    ]
